version: "3.8"

services:
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    container_name: db_postgres_todo
    # networks:
    #   - backend_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespass

  # backend:
  #   build:
  #     context: ./backend
  #   ports: 
  #    - 3000:3000
  #   container_name: backend_todo
  #   networks:
  #     - backend_db
  #     - backend_frontend
  #   depends_on:
  #     - db

  frontend:
    build:
      context: ./frontend
    ports:
     - 4173:4173
    container_name: frontend_todo
    # networks: backend_frontend
    # depends_on:
    # - backend

# networks:
#   backend_db:
#   backend_frontend