version: "3.8"

services:
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    container_name: db_postgres_todo
    networks:
      - back_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespass

  backend:
    build:
      context: ./backend
    ports: 
     - 3000:3000
    container_name: backend_todo
    networks:
      - back_db
    depends_on:
      - db

networks:
  back_db: